version: '3'
services:
  comgongBOT:
    build: .
    container_name: comgongbot-container
    image: comgongbot-image
    volumes:
      - .:/app
    restart: always
    ports:
      - 4000:4000
      - 5000:5000
      - 8080:8080
      - 9000:9000
      - 9099:9099